export const SHOELACE_BUTTON_BLUR = 'SNC_CMP_RDE#SHOELACE_BUTTON_BLUR';
export const SHOELACE_BUTTON_FOCUS = 'SNC_CMP_RDE#SHOELACE_BUTTON_FOCUS';
export const SHOELACE_BUTTON_INVALID = 'SNC_CMP_RDE#SHOELACE_BUTTON_INVALID';
export const BUTTON_CLICKED = 'SNC_CMP_RDE#BUTTON_CLICKED';